# Permalinks
permalink:           pretty

# Setup
title:               Munirah Bedaiwi
tagline:             A Data Science Blog
url:                 http://mnure97.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Munirah Bedaiwi
  
  email:             mbedaiwi1@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/mnure97

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
